# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.api.support_bundles_api import SupportBundlesApi  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestSupportBundlesApi(unittest.TestCase):
    """SupportBundlesApi unit test stubs"""

    def setUp(self):
        self.api = dd_sdk_1_0.api.support_bundles_api.SupportBundlesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v10_dd_systems_systemid_supports_support_bundles_delete(self):
        """Test case for rest_v10_dd_systems_systemid_supports_support_bundles_delete

        Delete all support bundles  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_supports_support_bundles_get(self):
        """Test case for rest_v10_dd_systems_systemid_supports_support_bundles_get

        List support bundles  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_supports_support_bundles_id_delete(self):
        """Test case for rest_v10_dd_systems_systemid_supports_support_bundles_id_delete

        Delete a support bundle  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_supports_support_bundles_post(self):
        """Test case for rest_v10_dd_systems_systemid_supports_support_bundles_post

        Create support bundle  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_supports_support_bundles_post(self):
        """Test case for rest_v20_dd_systems_systemid_supports_support_bundles_post

        Create support bundle asynchronously  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
