# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.api.vdisk_devices_api import VdiskDevicesApi  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestVdiskDevicesApi(unittest.TestCase):
    """VdiskDevicesApi unit test stubs"""

    def setUp(self):
        self.api = dd_sdk_1_0.api.vdisk_devices_api.VdiskDevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_delete(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_delete

        Delete a list of VDisk devices.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_get(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_get

        Get VDisk device information.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_delete(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_delete

        Delete a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_get(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_get

        Get a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_put(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_id_put

        Modify multiple VDisk devices.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_post(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_post

        Create a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_protocols_vdisk_devices_put(self):
        """Test case for rest_v10_dd_systems_systemid_protocols_vdisk_devices_put

        Modify a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_delete(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_delete

        Delete a list of VDisk devices.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_get(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_get

        Get VDisk device information.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_delete(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_delete

        Delete a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_get(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_get

        Get a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_put(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_id_put

        Modify a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_post(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_post

        Create a VDisk device.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_protocols_vdisk_devices_put(self):
        """Test case for rest_v20_dd_systems_systemid_protocols_vdisk_devices_put

        Modify one or more VDisk devices.  # noqa: E501
        """
        pass

    def test_rest_v30_dd_systems_systemid_protocols_vdisk_devices_id_get(self):
        """Test case for rest_v30_dd_systems_systemid_protocols_vdisk_devices_id_get

        Get a VDisk device.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
