# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.models.ddboost_client_sort_query import DdboostClientSortQuery  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestDdboostClientSortQuery(unittest.TestCase):
    """DdboostClientSortQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDdboostClientSortQuery(self):
        """Test DdboostClientSortQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dd_sdk_1_0.models.ddboost_client_sort_query.DdboostClientSortQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
