# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.api.sso_registration_api import SsoRegistrationApi  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestSsoRegistrationApi(unittest.TestCase):
    """SsoRegistrationApi unit test stubs"""

    def setUp(self):
        self.api = dd_sdk_1_0.api.sso_registration_api.SsoRegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v10_sso_registration_id_delete(self):
        """Test case for rest_v10_sso_registration_id_delete

        Delete OIDC provider info  # noqa: E501
        """
        pass

    def test_rest_v10_sso_registration_id_put(self):
        """Test case for rest_v10_sso_registration_id_put

        Update OIDC provider info  # noqa: E501
        """
        pass

    def test_rest_v10_sso_registration_post(self):
        """Test case for rest_v10_sso_registration_post

        Register DDR to OIDC provider.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
