# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.models.alerts_filter_query import AlertsFilterQuery  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestAlertsFilterQuery(unittest.TestCase):
    """AlertsFilterQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertsFilterQuery(self):
        """Test AlertsFilterQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dd_sdk_1_0.models.alerts_filter_query.AlertsFilterQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
