# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.models.asup_schedule_reset import AsupScheduleReset  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestAsupScheduleReset(unittest.TestCase):
    """AsupScheduleReset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsupScheduleReset(self):
        """Test AsupScheduleReset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dd_sdk_1_0.models.asup_schedule_reset.AsupScheduleReset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
