# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.models.mtree_stats_compression_details import MtreeStatsCompressionDetails  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestMtreeStatsCompressionDetails(unittest.TestCase):
    """MtreeStatsCompressionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMtreeStatsCompressionDetails(self):
        """Test MtreeStatsCompressionDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dd_sdk_1_0.models.mtree_stats_compression_details.MtreeStatsCompressionDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
