# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.api.mtrees_api import MtreesApi  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestMtreesApi(unittest.TestCase):
    """MtreesApi unit test stubs"""

    def setUp(self):
        self.api = dd_sdk_1_0.api.mtrees_api.MtreesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v10_dd_systems_systemid_mtrees_get(self):
        """Test case for rest_v10_dd_systems_systemid_mtrees_get

        Get MTree information.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_mtrees_id_delete(self):
        """Test case for rest_v10_dd_systems_systemid_mtrees_id_delete

        Delete an MTree.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_mtrees_id_get(self):
        """Test case for rest_v10_dd_systems_systemid_mtrees_id_get

        Get an MTree.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_mtrees_id_put(self):
        """Test case for rest_v10_dd_systems_systemid_mtrees_id_put

        Modify an MTree.  # noqa: E501
        """
        pass

    def test_rest_v10_dd_systems_systemid_mtrees_post(self):
        """Test case for rest_v10_dd_systems_systemid_mtrees_post

        Create an MTree.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_mtrees_get(self):
        """Test case for rest_v20_dd_systems_systemid_mtrees_get

        Get MTree information.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_mtrees_id_get(self):
        """Test case for rest_v20_dd_systems_systemid_mtrees_id_get

        Get an MTree.  # noqa: E501
        """
        pass

    def test_rest_v20_dd_systems_systemid_mtrees_id_put(self):
        """Test case for rest_v20_dd_systems_systemid_mtrees_id_put

        Modify an MTree.  # noqa: E501
        """
        pass

    def test_rest_v30_dd_systems_systemid_mtrees_get(self):
        """Test case for rest_v30_dd_systems_systemid_mtrees_get

        Get MTree information.  # noqa: E501
        """
        pass

    def test_rest_v30_dd_systems_systemid_mtrees_id_get(self):
        """Test case for rest_v30_dd_systems_systemid_mtrees_id_get

        Get an MTree.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
