# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dd_sdk_1_0
from dd_sdk_1_0.models.cloud_unit_sort_query import CloudUnitSortQuery  # noqa: E501
from dd_sdk_1_0.rest import ApiException


class TestCloudUnitSortQuery(unittest.TestCase):
    """CloudUnitSortQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudUnitSortQuery(self):
        """Test CloudUnitSortQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dd_sdk_1_0.models.cloud_unit_sort_query.CloudUnitSortQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
