# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dd_sdk_1_0.api_client import ApiClient


class TrustApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def rest_v10_trust_delete(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_delete(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.rest_v10_trust_delete_with_http_info(ca_info, **kwargs)  # noqa: E501
        else:
            (data) = self.rest_v10_trust_delete_with_http_info(ca_info, **kwargs)  # noqa: E501
            return data

    def rest_v10_trust_delete_with_http_info(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_delete_with_http_info(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_info']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rest_v10_trust_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_info' is set
        if self.api_client.client_side_validation and ('ca_info' not in params or
                                                       params['ca_info'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_info` when calling `rest_v10_trust_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ca_info' in params:
            body_params = params['ca_info']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/rest/v1.0/trust', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MtrustStatus',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def rest_v10_trust_get(self, **kwargs):  # noqa: E501
        """Establish mutual trust with DDR.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exclude_fields: Comma separated list of fields to be excluded from response object. Required and general fields such as paging will not be excluded. For example, \"msg, status,severity\" for an alert.  @#$type=commaSeparatedStrings
        :param str include_fields: Comma separated list of fields to be included in response object. For example, \"msg, status,severity\" for an alert.  @#$type=commaSeparatedStrings
        :return: TrustInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.rest_v10_trust_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.rest_v10_trust_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def rest_v10_trust_get_with_http_info(self, **kwargs):  # noqa: E501
        """Establish mutual trust with DDR.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str exclude_fields: Comma separated list of fields to be excluded from response object. Required and general fields such as paging will not be excluded. For example, \"msg, status,severity\" for an alert.  @#$type=commaSeparatedStrings
        :param str include_fields: Comma separated list of fields to be included in response object. For example, \"msg, status,severity\" for an alert.  @#$type=commaSeparatedStrings
        :return: TrustInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['exclude_fields', 'include_fields']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rest_v10_trust_get" % key
                )
            params[key] = val
        del params['kwargs']

        if self.api_client.client_side_validation and ('exclude_fields' in params and not re.search(r'^([^,]+,*)+$', params['exclude_fields'])):  # noqa: E501
            raise ValueError("Invalid value for parameter `exclude_fields` when calling `rest_v10_trust_get`, must conform to the pattern `/^([^,]+,*)+$/`")  # noqa: E501
        if self.api_client.client_side_validation and ('include_fields' in params and not re.search(r'^([^,]+,*)+$', params['include_fields'])):  # noqa: E501
            raise ValueError("Invalid value for parameter `include_fields` when calling `rest_v10_trust_get`, must conform to the pattern `/^([^,]+,*)+$/`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'exclude_fields' in params:
            query_params.append(('exclude_fields', params['exclude_fields']))  # noqa: E501
        if 'include_fields' in params:
            query_params.append(('include_fields', params['include_fields']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/rest/v1.0/trust', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TrustInfo',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def rest_v10_trust_post(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_post(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.rest_v10_trust_post_with_http_info(ca_info, **kwargs)  # noqa: E501
        else:
            (data) = self.rest_v10_trust_post_with_http_info(ca_info, **kwargs)  # noqa: E501
            return data

    def rest_v10_trust_post_with_http_info(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_post_with_http_info(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_info']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rest_v10_trust_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_info' is set
        if self.api_client.client_side_validation and ('ca_info' not in params or
                                                       params['ca_info'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_info` when calling `rest_v10_trust_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ca_info' in params:
            body_params = params['ca_info']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/rest/v1.0/trust', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MtrustStatus',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def rest_v10_trust_put(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_put(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.rest_v10_trust_put_with_http_info(ca_info, **kwargs)  # noqa: E501
        else:
            (data) = self.rest_v10_trust_put_with_http_info(ca_info, **kwargs)  # noqa: E501
            return data

    def rest_v10_trust_put_with_http_info(self, ca_info, **kwargs):  # noqa: E501
        """rest_v10_trust_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.rest_v10_trust_put_with_http_info(ca_info, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CaInfo ca_info: (required)
        :return: MtrustStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_info']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rest_v10_trust_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_info' is set
        if self.api_client.client_side_validation and ('ca_info' not in params or
                                                       params['ca_info'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_info` when calling `rest_v10_trust_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ca_info' in params:
            body_params = params['ca_info']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/xml', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/rest/v1.0/trust', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MtrustStatus',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
