# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class CertificateCreateInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cert_contents': 'CertContents',
        'csr_contents': 'CsrContents'
    }

    attribute_map = {
        'cert_contents': 'cert_contents',
        'csr_contents': 'csr_contents'
    }

    def __init__(self, cert_contents=None, csr_contents=None, _configuration=None):  # noqa: E501
        """CertificateCreateInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cert_contents = None
        self._csr_contents = None
        self.discriminator = None

        if cert_contents is not None:
            self.cert_contents = cert_contents
        if csr_contents is not None:
            self.csr_contents = csr_contents

    @property
    def cert_contents(self):
        """Gets the cert_contents of this CertificateCreateInfo.  # noqa: E501


        :return: The cert_contents of this CertificateCreateInfo.  # noqa: E501
        :rtype: CertContents
        """
        return self._cert_contents

    @cert_contents.setter
    def cert_contents(self, cert_contents):
        """Sets the cert_contents of this CertificateCreateInfo.


        :param cert_contents: The cert_contents of this CertificateCreateInfo.  # noqa: E501
        :type: CertContents
        """

        self._cert_contents = cert_contents

    @property
    def csr_contents(self):
        """Gets the csr_contents of this CertificateCreateInfo.  # noqa: E501


        :return: The csr_contents of this CertificateCreateInfo.  # noqa: E501
        :rtype: CsrContents
        """
        return self._csr_contents

    @csr_contents.setter
    def csr_contents(self, csr_contents):
        """Sets the csr_contents of this CertificateCreateInfo.


        :param csr_contents: The csr_contents of this CertificateCreateInfo.  # noqa: E501
        :type: CsrContents
        """

        self._csr_contents = csr_contents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CertificateCreateInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertificateCreateInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CertificateCreateInfo):
            return True

        return self.to_dict() != other.to_dict()
