# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class CloudProfileDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'cloud_provider': 'CloudProvider',
        'details': 'CloudProfileConfig',
        'link': 'list[RestLinkRep]'
    }

    attribute_map = {
        'id': 'id',
        'cloud_provider': 'cloud_provider',
        'details': 'details',
        'link': 'link'
    }

    def __init__(self, id=None, cloud_provider=None, details=None, link=None, _configuration=None):  # noqa: E501
        """CloudProfileDetail - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._cloud_provider = None
        self._details = None
        self._link = None
        self.discriminator = None

        self.id = id
        self.cloud_provider = cloud_provider
        self.details = details
        if link is not None:
            self.link = link

    @property
    def id(self):
        """Gets the id of this CloudProfileDetail.  # noqa: E501

        url-encoded name  # noqa: E501

        :return: The id of this CloudProfileDetail.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CloudProfileDetail.

        url-encoded name  # noqa: E501

        :param id: The id of this CloudProfileDetail.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def cloud_provider(self):
        """Gets the cloud_provider of this CloudProfileDetail.  # noqa: E501


        :return: The cloud_provider of this CloudProfileDetail.  # noqa: E501
        :rtype: CloudProvider
        """
        return self._cloud_provider

    @cloud_provider.setter
    def cloud_provider(self, cloud_provider):
        """Sets the cloud_provider of this CloudProfileDetail.


        :param cloud_provider: The cloud_provider of this CloudProfileDetail.  # noqa: E501
        :type: CloudProvider
        """
        if self._configuration.client_side_validation and cloud_provider is None:
            raise ValueError("Invalid value for `cloud_provider`, must not be `None`")  # noqa: E501

        self._cloud_provider = cloud_provider

    @property
    def details(self):
        """Gets the details of this CloudProfileDetail.  # noqa: E501


        :return: The details of this CloudProfileDetail.  # noqa: E501
        :rtype: CloudProfileConfig
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this CloudProfileDetail.


        :param details: The details of this CloudProfileDetail.  # noqa: E501
        :type: CloudProfileConfig
        """
        if self._configuration.client_side_validation and details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details

    @property
    def link(self):
        """Gets the link of this CloudProfileDetail.  # noqa: E501


        :return: The link of this CloudProfileDetail.  # noqa: E501
        :rtype: list[RestLinkRep]
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this CloudProfileDetail.


        :param link: The link of this CloudProfileDetail.  # noqa: E501
        :type: list[RestLinkRep]
        """

        self._link = link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudProfileDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudProfileDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CloudProfileDetail):
            return True

        return self.to_dict() != other.to_dict()
