# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class DataIP(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'local_data_ip': 'str',
        'remote_data_ip': 'list[str]'
    }

    attribute_map = {
        'local_data_ip': 'local_data_ip',
        'remote_data_ip': 'remote_data_ip'
    }

    def __init__(self, local_data_ip=None, remote_data_ip=None, _configuration=None):  # noqa: E501
        """DataIP - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._local_data_ip = None
        self._remote_data_ip = None
        self.discriminator = None

        if local_data_ip is not None:
            self.local_data_ip = local_data_ip
        if remote_data_ip is not None:
            self.remote_data_ip = remote_data_ip

    @property
    def local_data_ip(self):
        """Gets the local_data_ip of this DataIP.  # noqa: E501


        :return: The local_data_ip of this DataIP.  # noqa: E501
        :rtype: str
        """
        return self._local_data_ip

    @local_data_ip.setter
    def local_data_ip(self, local_data_ip):
        """Sets the local_data_ip of this DataIP.


        :param local_data_ip: The local_data_ip of this DataIP.  # noqa: E501
        :type: str
        """

        self._local_data_ip = local_data_ip

    @property
    def remote_data_ip(self):
        """Gets the remote_data_ip of this DataIP.  # noqa: E501


        :return: The remote_data_ip of this DataIP.  # noqa: E501
        :rtype: list[str]
        """
        return self._remote_data_ip

    @remote_data_ip.setter
    def remote_data_ip(self, remote_data_ip):
        """Sets the remote_data_ip of this DataIP.


        :param remote_data_ip: The remote_data_ip of this DataIP.  # noqa: E501
        :type: list[str]
        """

        self._remote_data_ip = remote_data_ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataIP, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataIP):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataIP):
            return True

        return self.to_dict() != other.to_dict()
