# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class EncryptionKeyManagerModify(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key_manager_operations': 'KeyManagerOperations',
        'key_manager_info': 'KeyManagerInfo'
    }

    attribute_map = {
        'key_manager_operations': 'key_manager_operations',
        'key_manager_info': 'key_manager_info'
    }

    def __init__(self, key_manager_operations=None, key_manager_info=None, _configuration=None):  # noqa: E501
        """EncryptionKeyManagerModify - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._key_manager_operations = None
        self._key_manager_info = None
        self.discriminator = None

        self.key_manager_operations = key_manager_operations
        if key_manager_info is not None:
            self.key_manager_info = key_manager_info

    @property
    def key_manager_operations(self):
        """Gets the key_manager_operations of this EncryptionKeyManagerModify.  # noqa: E501


        :return: The key_manager_operations of this EncryptionKeyManagerModify.  # noqa: E501
        :rtype: KeyManagerOperations
        """
        return self._key_manager_operations

    @key_manager_operations.setter
    def key_manager_operations(self, key_manager_operations):
        """Sets the key_manager_operations of this EncryptionKeyManagerModify.


        :param key_manager_operations: The key_manager_operations of this EncryptionKeyManagerModify.  # noqa: E501
        :type: KeyManagerOperations
        """
        if self._configuration.client_side_validation and key_manager_operations is None:
            raise ValueError("Invalid value for `key_manager_operations`, must not be `None`")  # noqa: E501

        self._key_manager_operations = key_manager_operations

    @property
    def key_manager_info(self):
        """Gets the key_manager_info of this EncryptionKeyManagerModify.  # noqa: E501


        :return: The key_manager_info of this EncryptionKeyManagerModify.  # noqa: E501
        :rtype: KeyManagerInfo
        """
        return self._key_manager_info

    @key_manager_info.setter
    def key_manager_info(self, key_manager_info):
        """Sets the key_manager_info of this EncryptionKeyManagerModify.


        :param key_manager_info: The key_manager_info of this EncryptionKeyManagerModify.  # noqa: E501
        :type: KeyManagerInfo
        """

        self._key_manager_info = key_manager_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EncryptionKeyManagerModify, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EncryptionKeyManagerModify):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EncryptionKeyManagerModify):
            return True

        return self.to_dict() != other.to_dict()
