# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class LicInfo20(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'feature': 'str',
        'type': 'LicType',
        'state': 'LicState',
        'expiration_epoch': 'int',
        'time_left_secs': 'int',
        'total_capacity_byte': 'float',
        'link': 'RestLinkRep'
    }

    attribute_map = {
        'id': 'id',
        'feature': 'feature',
        'type': 'type',
        'state': 'state',
        'expiration_epoch': 'expiration_epoch',
        'time_left_secs': 'time_left_secs',
        'total_capacity_byte': 'total_capacity_byte',
        'link': 'link'
    }

    def __init__(self, id=None, feature=None, type=None, state=None, expiration_epoch=None, time_left_secs=None, total_capacity_byte=None, link=None, _configuration=None):  # noqa: E501
        """LicInfo20 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._feature = None
        self._type = None
        self._state = None
        self._expiration_epoch = None
        self._time_left_secs = None
        self._total_capacity_byte = None
        self._link = None
        self.discriminator = None

        self.id = id
        self.feature = feature
        if type is not None:
            self.type = type
        if state is not None:
            self.state = state
        if expiration_epoch is not None:
            self.expiration_epoch = expiration_epoch
        if time_left_secs is not None:
            self.time_left_secs = time_left_secs
        if total_capacity_byte is not None:
            self.total_capacity_byte = total_capacity_byte
        if link is not None:
            self.link = link

    @property
    def id(self):
        """Gets the id of this LicInfo20.  # noqa: E501

        urlencoded feature  # noqa: E501

        :return: The id of this LicInfo20.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LicInfo20.

        urlencoded feature  # noqa: E501

        :param id: The id of this LicInfo20.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def feature(self):
        """Gets the feature of this LicInfo20.  # noqa: E501


        :return: The feature of this LicInfo20.  # noqa: E501
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """Sets the feature of this LicInfo20.


        :param feature: The feature of this LicInfo20.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and feature is None:
            raise ValueError("Invalid value for `feature`, must not be `None`")  # noqa: E501

        self._feature = feature

    @property
    def type(self):
        """Gets the type of this LicInfo20.  # noqa: E501


        :return: The type of this LicInfo20.  # noqa: E501
        :rtype: LicType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LicInfo20.


        :param type: The type of this LicInfo20.  # noqa: E501
        :type: LicType
        """

        self._type = type

    @property
    def state(self):
        """Gets the state of this LicInfo20.  # noqa: E501


        :return: The state of this LicInfo20.  # noqa: E501
        :rtype: LicState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this LicInfo20.


        :param state: The state of this LicInfo20.  # noqa: E501
        :type: LicState
        """

        self._state = state

    @property
    def expiration_epoch(self):
        """Gets the expiration_epoch of this LicInfo20.  # noqa: E501

        license expiration epoch  # noqa: E501

        :return: The expiration_epoch of this LicInfo20.  # noqa: E501
        :rtype: int
        """
        return self._expiration_epoch

    @expiration_epoch.setter
    def expiration_epoch(self, expiration_epoch):
        """Sets the expiration_epoch of this LicInfo20.

        license expiration epoch  # noqa: E501

        :param expiration_epoch: The expiration_epoch of this LicInfo20.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                expiration_epoch is not None and expiration_epoch < 0):  # noqa: E501
            raise ValueError("Invalid value for `expiration_epoch`, must be a value greater than or equal to `0`")  # noqa: E501

        self._expiration_epoch = expiration_epoch

    @property
    def time_left_secs(self):
        """Gets the time_left_secs of this LicInfo20.  # noqa: E501

        time left seconds in the current state  # noqa: E501

        :return: The time_left_secs of this LicInfo20.  # noqa: E501
        :rtype: int
        """
        return self._time_left_secs

    @time_left_secs.setter
    def time_left_secs(self, time_left_secs):
        """Sets the time_left_secs of this LicInfo20.

        time left seconds in the current state  # noqa: E501

        :param time_left_secs: The time_left_secs of this LicInfo20.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                time_left_secs is not None and time_left_secs < 0):  # noqa: E501
            raise ValueError("Invalid value for `time_left_secs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._time_left_secs = time_left_secs

    @property
    def total_capacity_byte(self):
        """Gets the total_capacity_byte of this LicInfo20.  # noqa: E501


        :return: The total_capacity_byte of this LicInfo20.  # noqa: E501
        :rtype: float
        """
        return self._total_capacity_byte

    @total_capacity_byte.setter
    def total_capacity_byte(self, total_capacity_byte):
        """Sets the total_capacity_byte of this LicInfo20.


        :param total_capacity_byte: The total_capacity_byte of this LicInfo20.  # noqa: E501
        :type: float
        """

        self._total_capacity_byte = total_capacity_byte

    @property
    def link(self):
        """Gets the link of this LicInfo20.  # noqa: E501


        :return: The link of this LicInfo20.  # noqa: E501
        :rtype: RestLinkRep
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this LicInfo20.


        :param link: The link of this LicInfo20.  # noqa: E501
        :type: RestLinkRep
        """

        self._link = link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LicInfo20, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LicInfo20):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LicInfo20):
            return True

        return self.to_dict() != other.to_dict()
