# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class MtreeCompressionInfoDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tier': 'TierType',
        'start_epoch': 'int',
        'end_epoch': 'int',
        'pre_compression_in_bytes': 'int',
        'post_compression_in_bytes': 'int',
        'local_compression_factor': 'float',
        'global_compression_factor': 'float',
        'total_compression_factor': 'float',
        'reduction_in_percentage': 'float'
    }

    attribute_map = {
        'tier': 'tier',
        'start_epoch': 'start_epoch',
        'end_epoch': 'end_epoch',
        'pre_compression_in_bytes': 'pre_compression_in_bytes',
        'post_compression_in_bytes': 'post_compression_in_bytes',
        'local_compression_factor': 'local_compression_factor',
        'global_compression_factor': 'global_compression_factor',
        'total_compression_factor': 'total_compression_factor',
        'reduction_in_percentage': 'reduction_in_percentage'
    }

    def __init__(self, tier=None, start_epoch=None, end_epoch=None, pre_compression_in_bytes=None, post_compression_in_bytes=None, local_compression_factor=None, global_compression_factor=None, total_compression_factor=None, reduction_in_percentage=None, _configuration=None):  # noqa: E501
        """MtreeCompressionInfoDetail - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._tier = None
        self._start_epoch = None
        self._end_epoch = None
        self._pre_compression_in_bytes = None
        self._post_compression_in_bytes = None
        self._local_compression_factor = None
        self._global_compression_factor = None
        self._total_compression_factor = None
        self._reduction_in_percentage = None
        self.discriminator = None

        self.tier = tier
        if start_epoch is not None:
            self.start_epoch = start_epoch
        if end_epoch is not None:
            self.end_epoch = end_epoch
        if pre_compression_in_bytes is not None:
            self.pre_compression_in_bytes = pre_compression_in_bytes
        if post_compression_in_bytes is not None:
            self.post_compression_in_bytes = post_compression_in_bytes
        if local_compression_factor is not None:
            self.local_compression_factor = local_compression_factor
        if global_compression_factor is not None:
            self.global_compression_factor = global_compression_factor
        if total_compression_factor is not None:
            self.total_compression_factor = total_compression_factor
        if reduction_in_percentage is not None:
            self.reduction_in_percentage = reduction_in_percentage

    @property
    def tier(self):
        """Gets the tier of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The tier of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: TierType
        """
        return self._tier

    @tier.setter
    def tier(self, tier):
        """Sets the tier of this MtreeCompressionInfoDetail.


        :param tier: The tier of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: TierType
        """
        if self._configuration.client_side_validation and tier is None:
            raise ValueError("Invalid value for `tier`, must not be `None`")  # noqa: E501

        self._tier = tier

    @property
    def start_epoch(self):
        """Gets the start_epoch of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The start_epoch of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: int
        """
        return self._start_epoch

    @start_epoch.setter
    def start_epoch(self, start_epoch):
        """Sets the start_epoch of this MtreeCompressionInfoDetail.


        :param start_epoch: The start_epoch of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                start_epoch is not None and start_epoch < 0):  # noqa: E501
            raise ValueError("Invalid value for `start_epoch`, must be a value greater than or equal to `0`")  # noqa: E501

        self._start_epoch = start_epoch

    @property
    def end_epoch(self):
        """Gets the end_epoch of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The end_epoch of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: int
        """
        return self._end_epoch

    @end_epoch.setter
    def end_epoch(self, end_epoch):
        """Sets the end_epoch of this MtreeCompressionInfoDetail.


        :param end_epoch: The end_epoch of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                end_epoch is not None and end_epoch < 0):  # noqa: E501
            raise ValueError("Invalid value for `end_epoch`, must be a value greater than or equal to `0`")  # noqa: E501

        self._end_epoch = end_epoch

    @property
    def pre_compression_in_bytes(self):
        """Gets the pre_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The pre_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: int
        """
        return self._pre_compression_in_bytes

    @pre_compression_in_bytes.setter
    def pre_compression_in_bytes(self, pre_compression_in_bytes):
        """Sets the pre_compression_in_bytes of this MtreeCompressionInfoDetail.


        :param pre_compression_in_bytes: The pre_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                pre_compression_in_bytes is not None and pre_compression_in_bytes < 0):  # noqa: E501
            raise ValueError("Invalid value for `pre_compression_in_bytes`, must be a value greater than or equal to `0`")  # noqa: E501

        self._pre_compression_in_bytes = pre_compression_in_bytes

    @property
    def post_compression_in_bytes(self):
        """Gets the post_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The post_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: int
        """
        return self._post_compression_in_bytes

    @post_compression_in_bytes.setter
    def post_compression_in_bytes(self, post_compression_in_bytes):
        """Sets the post_compression_in_bytes of this MtreeCompressionInfoDetail.


        :param post_compression_in_bytes: The post_compression_in_bytes of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                post_compression_in_bytes is not None and post_compression_in_bytes < 0):  # noqa: E501
            raise ValueError("Invalid value for `post_compression_in_bytes`, must be a value greater than or equal to `0`")  # noqa: E501

        self._post_compression_in_bytes = post_compression_in_bytes

    @property
    def local_compression_factor(self):
        """Gets the local_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The local_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: float
        """
        return self._local_compression_factor

    @local_compression_factor.setter
    def local_compression_factor(self, local_compression_factor):
        """Sets the local_compression_factor of this MtreeCompressionInfoDetail.


        :param local_compression_factor: The local_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: float
        """

        self._local_compression_factor = local_compression_factor

    @property
    def global_compression_factor(self):
        """Gets the global_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The global_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: float
        """
        return self._global_compression_factor

    @global_compression_factor.setter
    def global_compression_factor(self, global_compression_factor):
        """Sets the global_compression_factor of this MtreeCompressionInfoDetail.


        :param global_compression_factor: The global_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: float
        """

        self._global_compression_factor = global_compression_factor

    @property
    def total_compression_factor(self):
        """Gets the total_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The total_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: float
        """
        return self._total_compression_factor

    @total_compression_factor.setter
    def total_compression_factor(self, total_compression_factor):
        """Sets the total_compression_factor of this MtreeCompressionInfoDetail.


        :param total_compression_factor: The total_compression_factor of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: float
        """

        self._total_compression_factor = total_compression_factor

    @property
    def reduction_in_percentage(self):
        """Gets the reduction_in_percentage of this MtreeCompressionInfoDetail.  # noqa: E501


        :return: The reduction_in_percentage of this MtreeCompressionInfoDetail.  # noqa: E501
        :rtype: float
        """
        return self._reduction_in_percentage

    @reduction_in_percentage.setter
    def reduction_in_percentage(self, reduction_in_percentage):
        """Sets the reduction_in_percentage of this MtreeCompressionInfoDetail.


        :param reduction_in_percentage: The reduction_in_percentage of this MtreeCompressionInfoDetail.  # noqa: E501
        :type: float
        """

        self._reduction_in_percentage = reduction_in_percentage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MtreeCompressionInfoDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MtreeCompressionInfoDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MtreeCompressionInfoDetail):
            return True

        return self.to_dict() != other.to_dict()
