# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class ServiceNtpInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'current_time_epoch': 'str',
        'synced_time_epoch': 'str',
        'synced_server': 'str',
        'servers': 'ServersList',
        'link': 'list[RestLinkRep]'
    }

    attribute_map = {
        'status': 'status',
        'current_time_epoch': 'current_time_epoch',
        'synced_time_epoch': 'synced_time_epoch',
        'synced_server': 'synced_server',
        'servers': 'servers',
        'link': 'link'
    }

    def __init__(self, status=None, current_time_epoch=None, synced_time_epoch=None, synced_server=None, servers=None, link=None, _configuration=None):  # noqa: E501
        """ServiceNtpInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._current_time_epoch = None
        self._synced_time_epoch = None
        self._synced_server = None
        self._servers = None
        self._link = None
        self.discriminator = None

        if status is not None:
            self.status = status
        self.current_time_epoch = current_time_epoch
        self.synced_time_epoch = synced_time_epoch
        self.synced_server = synced_server
        if servers is not None:
            self.servers = servers
        if link is not None:
            self.link = link

    @property
    def status(self):
        """Gets the status of this ServiceNtpInfo.  # noqa: E501


        :return: The status of this ServiceNtpInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ServiceNtpInfo.


        :param status: The status of this ServiceNtpInfo.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def current_time_epoch(self):
        """Gets the current_time_epoch of this ServiceNtpInfo.  # noqa: E501


        :return: The current_time_epoch of this ServiceNtpInfo.  # noqa: E501
        :rtype: str
        """
        return self._current_time_epoch

    @current_time_epoch.setter
    def current_time_epoch(self, current_time_epoch):
        """Sets the current_time_epoch of this ServiceNtpInfo.


        :param current_time_epoch: The current_time_epoch of this ServiceNtpInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and current_time_epoch is None:
            raise ValueError("Invalid value for `current_time_epoch`, must not be `None`")  # noqa: E501

        self._current_time_epoch = current_time_epoch

    @property
    def synced_time_epoch(self):
        """Gets the synced_time_epoch of this ServiceNtpInfo.  # noqa: E501


        :return: The synced_time_epoch of this ServiceNtpInfo.  # noqa: E501
        :rtype: str
        """
        return self._synced_time_epoch

    @synced_time_epoch.setter
    def synced_time_epoch(self, synced_time_epoch):
        """Sets the synced_time_epoch of this ServiceNtpInfo.


        :param synced_time_epoch: The synced_time_epoch of this ServiceNtpInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and synced_time_epoch is None:
            raise ValueError("Invalid value for `synced_time_epoch`, must not be `None`")  # noqa: E501

        self._synced_time_epoch = synced_time_epoch

    @property
    def synced_server(self):
        """Gets the synced_server of this ServiceNtpInfo.  # noqa: E501


        :return: The synced_server of this ServiceNtpInfo.  # noqa: E501
        :rtype: str
        """
        return self._synced_server

    @synced_server.setter
    def synced_server(self, synced_server):
        """Sets the synced_server of this ServiceNtpInfo.


        :param synced_server: The synced_server of this ServiceNtpInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and synced_server is None:
            raise ValueError("Invalid value for `synced_server`, must not be `None`")  # noqa: E501

        self._synced_server = synced_server

    @property
    def servers(self):
        """Gets the servers of this ServiceNtpInfo.  # noqa: E501


        :return: The servers of this ServiceNtpInfo.  # noqa: E501
        :rtype: ServersList
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this ServiceNtpInfo.


        :param servers: The servers of this ServiceNtpInfo.  # noqa: E501
        :type: ServersList
        """

        self._servers = servers

    @property
    def link(self):
        """Gets the link of this ServiceNtpInfo.  # noqa: E501


        :return: The link of this ServiceNtpInfo.  # noqa: E501
        :rtype: list[RestLinkRep]
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this ServiceNtpInfo.


        :param link: The link of this ServiceNtpInfo.  # noqa: E501
        :type: list[RestLinkRep]
        """

        self._link = link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceNtpInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceNtpInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServiceNtpInfo):
            return True

        return self.to_dict() != other.to_dict()
