# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class SnmpAccessHost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'community': 'str',
        'access': 'SnmpAccess',
        'hosts': 'list[str]'
    }

    attribute_map = {
        'community': 'community',
        'access': 'access',
        'hosts': 'hosts'
    }

    def __init__(self, community=None, access=None, hosts=None, _configuration=None):  # noqa: E501
        """SnmpAccessHost - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._community = None
        self._access = None
        self._hosts = None
        self.discriminator = None

        self.community = community
        self.access = access
        if hosts is not None:
            self.hosts = hosts

    @property
    def community(self):
        """Gets the community of this SnmpAccessHost.  # noqa: E501


        :return: The community of this SnmpAccessHost.  # noqa: E501
        :rtype: str
        """
        return self._community

    @community.setter
    def community(self, community):
        """Sets the community of this SnmpAccessHost.


        :param community: The community of this SnmpAccessHost.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and community is None:
            raise ValueError("Invalid value for `community`, must not be `None`")  # noqa: E501

        self._community = community

    @property
    def access(self):
        """Gets the access of this SnmpAccessHost.  # noqa: E501


        :return: The access of this SnmpAccessHost.  # noqa: E501
        :rtype: SnmpAccess
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this SnmpAccessHost.


        :param access: The access of this SnmpAccessHost.  # noqa: E501
        :type: SnmpAccess
        """
        if self._configuration.client_side_validation and access is None:
            raise ValueError("Invalid value for `access`, must not be `None`")  # noqa: E501

        self._access = access

    @property
    def hosts(self):
        """Gets the hosts of this SnmpAccessHost.  # noqa: E501


        :return: The hosts of this SnmpAccessHost.  # noqa: E501
        :rtype: list[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this SnmpAccessHost.


        :param hosts: The hosts of this SnmpAccessHost.  # noqa: E501
        :type: list[str]
        """

        self._hosts = hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SnmpAccessHost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnmpAccessHost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SnmpAccessHost):
            return True

        return self.to_dict() != other.to_dict()
