# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class TenantUnitInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'uuid': 'str',
        'tenant_name': 'str',
        'pre_comp_bytes': 'int',
        'hostname': 'str',
        'security_mode': 'SecurityMode',
        'number_of_mtrees': 'int',
        'link': 'RestLinkRep'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'uuid': 'uuid',
        'tenant_name': 'tenant_name',
        'pre_comp_bytes': 'pre_comp_bytes',
        'hostname': 'hostname',
        'security_mode': 'security_mode',
        'number_of_mtrees': 'number_of_mtrees',
        'link': 'link'
    }

    def __init__(self, id=None, name=None, uuid=None, tenant_name=None, pre_comp_bytes=None, hostname=None, security_mode=None, number_of_mtrees=None, link=None, _configuration=None):  # noqa: E501
        """TenantUnitInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._uuid = None
        self._tenant_name = None
        self._pre_comp_bytes = None
        self._hostname = None
        self._security_mode = None
        self._number_of_mtrees = None
        self._link = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.uuid = uuid
        if tenant_name is not None:
            self.tenant_name = tenant_name
        if pre_comp_bytes is not None:
            self.pre_comp_bytes = pre_comp_bytes
        if hostname is not None:
            self.hostname = hostname
        if security_mode is not None:
            self.security_mode = security_mode
        if number_of_mtrees is not None:
            self.number_of_mtrees = number_of_mtrees
        if link is not None:
            self.link = link

    @property
    def id(self):
        """Gets the id of this TenantUnitInfo.  # noqa: E501

        url-encoded name  # noqa: E501

        :return: The id of this TenantUnitInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TenantUnitInfo.

        url-encoded name  # noqa: E501

        :param id: The id of this TenantUnitInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TenantUnitInfo.  # noqa: E501


        :return: The name of this TenantUnitInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TenantUnitInfo.


        :param name: The name of this TenantUnitInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def uuid(self):
        """Gets the uuid of this TenantUnitInfo.  # noqa: E501


        :return: The uuid of this TenantUnitInfo.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TenantUnitInfo.


        :param uuid: The uuid of this TenantUnitInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def tenant_name(self):
        """Gets the tenant_name of this TenantUnitInfo.  # noqa: E501


        :return: The tenant_name of this TenantUnitInfo.  # noqa: E501
        :rtype: str
        """
        return self._tenant_name

    @tenant_name.setter
    def tenant_name(self, tenant_name):
        """Sets the tenant_name of this TenantUnitInfo.


        :param tenant_name: The tenant_name of this TenantUnitInfo.  # noqa: E501
        :type: str
        """

        self._tenant_name = tenant_name

    @property
    def pre_comp_bytes(self):
        """Gets the pre_comp_bytes of this TenantUnitInfo.  # noqa: E501


        :return: The pre_comp_bytes of this TenantUnitInfo.  # noqa: E501
        :rtype: int
        """
        return self._pre_comp_bytes

    @pre_comp_bytes.setter
    def pre_comp_bytes(self, pre_comp_bytes):
        """Sets the pre_comp_bytes of this TenantUnitInfo.


        :param pre_comp_bytes: The pre_comp_bytes of this TenantUnitInfo.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                pre_comp_bytes is not None and pre_comp_bytes < 0):  # noqa: E501
            raise ValueError("Invalid value for `pre_comp_bytes`, must be a value greater than or equal to `0`")  # noqa: E501

        self._pre_comp_bytes = pre_comp_bytes

    @property
    def hostname(self):
        """Gets the hostname of this TenantUnitInfo.  # noqa: E501


        :return: The hostname of this TenantUnitInfo.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this TenantUnitInfo.


        :param hostname: The hostname of this TenantUnitInfo.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def security_mode(self):
        """Gets the security_mode of this TenantUnitInfo.  # noqa: E501


        :return: The security_mode of this TenantUnitInfo.  # noqa: E501
        :rtype: SecurityMode
        """
        return self._security_mode

    @security_mode.setter
    def security_mode(self, security_mode):
        """Sets the security_mode of this TenantUnitInfo.


        :param security_mode: The security_mode of this TenantUnitInfo.  # noqa: E501
        :type: SecurityMode
        """

        self._security_mode = security_mode

    @property
    def number_of_mtrees(self):
        """Gets the number_of_mtrees of this TenantUnitInfo.  # noqa: E501


        :return: The number_of_mtrees of this TenantUnitInfo.  # noqa: E501
        :rtype: int
        """
        return self._number_of_mtrees

    @number_of_mtrees.setter
    def number_of_mtrees(self, number_of_mtrees):
        """Sets the number_of_mtrees of this TenantUnitInfo.


        :param number_of_mtrees: The number_of_mtrees of this TenantUnitInfo.  # noqa: E501
        :type: int
        """

        self._number_of_mtrees = number_of_mtrees

    @property
    def link(self):
        """Gets the link of this TenantUnitInfo.  # noqa: E501


        :return: The link of this TenantUnitInfo.  # noqa: E501
        :rtype: RestLinkRep
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this TenantUnitInfo.


        :param link: The link of this TenantUnitInfo.  # noqa: E501
        :type: RestLinkRep
        """

        self._link = link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TenantUnitInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TenantUnitInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TenantUnitInfo):
            return True

        return self.to_dict() != other.to_dict()
