# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class VdiskStimgModify20(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'VdiskStimgModifyOps',
        'set_retention_time_request': 'VdiskStimgSetRetentionTime',
        'kvm_set_clear_request': 'VdiskStimgKvmSetClear',
        'attach_request': 'VdiskStimgAttachStimg2Device',
        'mark_tier_movement_request': 'VdiskStimgMarkTierMovement'
    }

    attribute_map = {
        'operation': 'operation',
        'set_retention_time_request': 'set_retention_time_request',
        'kvm_set_clear_request': 'kvm_set_clear_request',
        'attach_request': 'attach_request',
        'mark_tier_movement_request': 'mark_tier_movement_request'
    }

    def __init__(self, operation=None, set_retention_time_request=None, kvm_set_clear_request=None, attach_request=None, mark_tier_movement_request=None, _configuration=None):  # noqa: E501
        """VdiskStimgModify20 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._operation = None
        self._set_retention_time_request = None
        self._kvm_set_clear_request = None
        self._attach_request = None
        self._mark_tier_movement_request = None
        self.discriminator = None

        self.operation = operation
        if set_retention_time_request is not None:
            self.set_retention_time_request = set_retention_time_request
        if kvm_set_clear_request is not None:
            self.kvm_set_clear_request = kvm_set_clear_request
        if attach_request is not None:
            self.attach_request = attach_request
        if mark_tier_movement_request is not None:
            self.mark_tier_movement_request = mark_tier_movement_request

    @property
    def operation(self):
        """Gets the operation of this VdiskStimgModify20.  # noqa: E501


        :return: The operation of this VdiskStimgModify20.  # noqa: E501
        :rtype: VdiskStimgModifyOps
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this VdiskStimgModify20.


        :param operation: The operation of this VdiskStimgModify20.  # noqa: E501
        :type: VdiskStimgModifyOps
        """
        if self._configuration.client_side_validation and operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def set_retention_time_request(self):
        """Gets the set_retention_time_request of this VdiskStimgModify20.  # noqa: E501


        :return: The set_retention_time_request of this VdiskStimgModify20.  # noqa: E501
        :rtype: VdiskStimgSetRetentionTime
        """
        return self._set_retention_time_request

    @set_retention_time_request.setter
    def set_retention_time_request(self, set_retention_time_request):
        """Sets the set_retention_time_request of this VdiskStimgModify20.


        :param set_retention_time_request: The set_retention_time_request of this VdiskStimgModify20.  # noqa: E501
        :type: VdiskStimgSetRetentionTime
        """

        self._set_retention_time_request = set_retention_time_request

    @property
    def kvm_set_clear_request(self):
        """Gets the kvm_set_clear_request of this VdiskStimgModify20.  # noqa: E501


        :return: The kvm_set_clear_request of this VdiskStimgModify20.  # noqa: E501
        :rtype: VdiskStimgKvmSetClear
        """
        return self._kvm_set_clear_request

    @kvm_set_clear_request.setter
    def kvm_set_clear_request(self, kvm_set_clear_request):
        """Sets the kvm_set_clear_request of this VdiskStimgModify20.


        :param kvm_set_clear_request: The kvm_set_clear_request of this VdiskStimgModify20.  # noqa: E501
        :type: VdiskStimgKvmSetClear
        """

        self._kvm_set_clear_request = kvm_set_clear_request

    @property
    def attach_request(self):
        """Gets the attach_request of this VdiskStimgModify20.  # noqa: E501


        :return: The attach_request of this VdiskStimgModify20.  # noqa: E501
        :rtype: VdiskStimgAttachStimg2Device
        """
        return self._attach_request

    @attach_request.setter
    def attach_request(self, attach_request):
        """Sets the attach_request of this VdiskStimgModify20.


        :param attach_request: The attach_request of this VdiskStimgModify20.  # noqa: E501
        :type: VdiskStimgAttachStimg2Device
        """

        self._attach_request = attach_request

    @property
    def mark_tier_movement_request(self):
        """Gets the mark_tier_movement_request of this VdiskStimgModify20.  # noqa: E501


        :return: The mark_tier_movement_request of this VdiskStimgModify20.  # noqa: E501
        :rtype: VdiskStimgMarkTierMovement
        """
        return self._mark_tier_movement_request

    @mark_tier_movement_request.setter
    def mark_tier_movement_request(self, mark_tier_movement_request):
        """Sets the mark_tier_movement_request of this VdiskStimgModify20.


        :param mark_tier_movement_request: The mark_tier_movement_request of this VdiskStimgModify20.  # noqa: E501
        :type: VdiskStimgMarkTierMovement
        """

        self._mark_tier_movement_request = mark_tier_movement_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VdiskStimgModify20, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VdiskStimgModify20):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VdiskStimgModify20):
            return True

        return self.to_dict() != other.to_dict()
