# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class VdiskStimgCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'src_device_wwnn': 'str',
        'dest_device_wwnn': 'str',
        'dest_devgrp_guid': 'str',
        '_property': 'list[KeyValuePair]'
    }

    attribute_map = {
        'src_device_wwnn': 'src_device_wwnn',
        'dest_device_wwnn': 'dest_device_wwnn',
        'dest_devgrp_guid': 'dest_devgrp_guid',
        '_property': 'property'
    }

    def __init__(self, src_device_wwnn=None, dest_device_wwnn=None, dest_devgrp_guid=None, _property=None, _configuration=None):  # noqa: E501
        """VdiskStimgCreate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._src_device_wwnn = None
        self._dest_device_wwnn = None
        self._dest_devgrp_guid = None
        self.__property = None
        self.discriminator = None

        self.src_device_wwnn = src_device_wwnn
        if dest_device_wwnn is not None:
            self.dest_device_wwnn = dest_device_wwnn
        if dest_devgrp_guid is not None:
            self.dest_devgrp_guid = dest_devgrp_guid
        if _property is not None:
            self._property = _property

    @property
    def src_device_wwnn(self):
        """Gets the src_device_wwnn of this VdiskStimgCreate.  # noqa: E501

        required device wwnn  # noqa: E501

        :return: The src_device_wwnn of this VdiskStimgCreate.  # noqa: E501
        :rtype: str
        """
        return self._src_device_wwnn

    @src_device_wwnn.setter
    def src_device_wwnn(self, src_device_wwnn):
        """Sets the src_device_wwnn of this VdiskStimgCreate.

        required device wwnn  # noqa: E501

        :param src_device_wwnn: The src_device_wwnn of this VdiskStimgCreate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and src_device_wwnn is None:
            raise ValueError("Invalid value for `src_device_wwnn`, must not be `None`")  # noqa: E501

        self._src_device_wwnn = src_device_wwnn

    @property
    def dest_device_wwnn(self):
        """Gets the dest_device_wwnn of this VdiskStimgCreate.  # noqa: E501

        wwnn  # noqa: E501

        :return: The dest_device_wwnn of this VdiskStimgCreate.  # noqa: E501
        :rtype: str
        """
        return self._dest_device_wwnn

    @dest_device_wwnn.setter
    def dest_device_wwnn(self, dest_device_wwnn):
        """Sets the dest_device_wwnn of this VdiskStimgCreate.

        wwnn  # noqa: E501

        :param dest_device_wwnn: The dest_device_wwnn of this VdiskStimgCreate.  # noqa: E501
        :type: str
        """

        self._dest_device_wwnn = dest_device_wwnn

    @property
    def dest_devgrp_guid(self):
        """Gets the dest_devgrp_guid of this VdiskStimgCreate.  # noqa: E501

        GUID  # noqa: E501

        :return: The dest_devgrp_guid of this VdiskStimgCreate.  # noqa: E501
        :rtype: str
        """
        return self._dest_devgrp_guid

    @dest_devgrp_guid.setter
    def dest_devgrp_guid(self, dest_devgrp_guid):
        """Sets the dest_devgrp_guid of this VdiskStimgCreate.

        GUID  # noqa: E501

        :param dest_devgrp_guid: The dest_devgrp_guid of this VdiskStimgCreate.  # noqa: E501
        :type: str
        """

        self._dest_devgrp_guid = dest_devgrp_guid

    @property
    def _property(self):
        """Gets the _property of this VdiskStimgCreate.  # noqa: E501


        :return: The _property of this VdiskStimgCreate.  # noqa: E501
        :rtype: list[KeyValuePair]
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this VdiskStimgCreate.


        :param _property: The _property of this VdiskStimgCreate.  # noqa: E501
        :type: list[KeyValuePair]
        """

        self.__property = _property

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VdiskStimgCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VdiskStimgCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VdiskStimgCreate):
            return True

        return self.to_dict() != other.to_dict()
