# coding: utf-8

"""
    DataDomain Rest API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from dd_sdk_1_0.configuration import Configuration


class VdiskDevicesModifyItem20(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wwnn': 'str',
        'device_modify': 'VdiskDeviceModify20'
    }

    attribute_map = {
        'wwnn': 'wwnn',
        'device_modify': 'device_modify'
    }

    def __init__(self, wwnn=None, device_modify=None, _configuration=None):  # noqa: E501
        """VdiskDevicesModifyItem20 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._wwnn = None
        self._device_modify = None
        self.discriminator = None

        self.wwnn = wwnn
        self.device_modify = device_modify

    @property
    def wwnn(self):
        """Gets the wwnn of this VdiskDevicesModifyItem20.  # noqa: E501


        :return: The wwnn of this VdiskDevicesModifyItem20.  # noqa: E501
        :rtype: str
        """
        return self._wwnn

    @wwnn.setter
    def wwnn(self, wwnn):
        """Sets the wwnn of this VdiskDevicesModifyItem20.


        :param wwnn: The wwnn of this VdiskDevicesModifyItem20.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and wwnn is None:
            raise ValueError("Invalid value for `wwnn`, must not be `None`")  # noqa: E501

        self._wwnn = wwnn

    @property
    def device_modify(self):
        """Gets the device_modify of this VdiskDevicesModifyItem20.  # noqa: E501


        :return: The device_modify of this VdiskDevicesModifyItem20.  # noqa: E501
        :rtype: VdiskDeviceModify20
        """
        return self._device_modify

    @device_modify.setter
    def device_modify(self, device_modify):
        """Sets the device_modify of this VdiskDevicesModifyItem20.


        :param device_modify: The device_modify of this VdiskDevicesModifyItem20.  # noqa: E501
        :type: VdiskDeviceModify20
        """
        if self._configuration.client_side_validation and device_modify is None:
            raise ValueError("Invalid value for `device_modify`, must not be `None`")  # noqa: E501

        self._device_modify = device_modify

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VdiskDevicesModifyItem20, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VdiskDevicesModifyItem20):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VdiskDevicesModifyItem20):
            return True

        return self.to_dict() != other.to_dict()
